[package]
name = "no_key_wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-cdk = "0.5.2"
ic-cdk-macros = "0.5.2"
candid = "0.7.14"
serde = "1"
rlp = "0.5.2"
ethereum = "0.12.0"
getrandom = { version = "0.2", features = ["js"] }
sha3 = "0.10.6"
